services:

  nginx:
    build: ./requirements/nginx
    image: nginx
    pull_policy: never
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    pull_policy: never
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_password
      - admin
      - credentials

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    pull_policy: never
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password

  redis:
    build: ./requirements/redis
    image: redis
    pull_policy: never
    container_name: redis
    networks:
      - inception
    restart: unless-stopped

  ftp:
    build: ./requirements/ftp
    image: ftp
    pull_policy: never
    container_name: ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    secrets:
      - ftp_password

  static:
    build: ./requirements/static
    image: static
    pull_policy: never
    container_name: static
    ports:
      - "80:80"
    networks:
      - inception
    restart: unless-stopped

  adminer:
    build: ./requirements/adminer
    image: adminer
    pull_policy: never
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: unless-stopped

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alfsanch/data/wordpress
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/alfsanch/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  admin:
    file: ../secrets/admin.txt
  credentials:
    file: ../secrets/credentials.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
